export const ADD_INGREDIANT = 'ADD_INGREDIANT';
export const REMOVE_INGREDIANT = 'REMOVE_INGREDIANT';
export const SET_INGREDIANTS = 'SET_INGREDIANTS';
export const FATCH_INGREDIANS_FAILED = 'FATCH_INGREDIANS_FAILED';
export const INIT_INGREDIANTS = 'INIT_INGREDIANTS';

export const PURCHASE_BURGER_START = 'PURCHASE_BURGER_START';
export const PURCHASE_BURGER_SUCCESS = 'PURCHASE_BURGER_SUCCESS';
export const PURCHASE_BURGER_FAIL = 'PURCHASE_BURGER_FAIL';
export const PURCHASE_INIT = 'PURCHASE_INIT';
export const PURCHASE_BURGER = 'PURCHASE_BURGER';

export const FATCH_ORDERS_START = 'FATCH_ORDERS_START';
export const FATCH_ORDERS_SUCCESS = 'FATCH_ORDERS_SUCCESS';
export const FATCH_ORDERS_FAIL = 'FATCH_ORDERS_FAIL';
export const FATCH_ORDERS = 'FATCH_ORDERS';

export const AUTH_CHECK_STATE = 'AUTH_CHECKL_STATE';
export const AUTH_USER= 'AUTH_USER';
export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_INITITAVE_LOGOUT = 'AUTH_INITITAVE_LOGOUT';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_CHECK_TIMEOUT = 'AUTH_CHECK_TIMEOUT';

export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';